name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch latest toolchain
      run: make pull

    - name: Fetch source
      run: make -f makefile.github fetch

    - name: Configure source
      run: make -f makefile.github configure

    - name: Make bash
      run: make -f makefile.github compile

    - name: Dist a binary
      run: make -f makefile.github dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minui-bash
        path: build/tg5040
        retention-days: 7
